### PR TITLE
Add a new restore logic for startup

### PR DESCRIPTION
**Pull request by rytswd**
This restore almost mirrors the existing restore, but does more aggressive clean-up.

I could refactor the original restore function to reduce duplicated code, but kept it with the simplest form for now. (As I'm not so versed in Elisp, I wasn't too sure if I could get it really clean 🙇)

### CODE REVIEW

**Comment by mclearc** [comment]
Cool -- this looks great. I'm also going to be adding new interactive per project restore session functionality soon. Thanks!

**Comment by rytswd** [comment]
Thanks for the quick review!
I think it would be great to restore the last tab open, split frames, and even potentially include process buffers such as magit, elfeed, etc. -- it may add too much complexity, though, so just sharing some ideas ☺️

**Comment by ParetoOptimalDev** [comment]
> Thanks for the quick review! I think it would be great to restore the last tab open, split frames, and even potentially include process buffers such as magit, elfeed, etc. -- it may add too much complexity, though, so just sharing some ideas relaxed

The only solution I know of going to that extent before is https://github.com/Bad-ptr/persp-mode.el.

For instance throughout issues I've seen the author respond with "how to restore terminals" and other tricky cases like here:

https://github.com/Bad-ptr/persp-mode.el/issues/72#issuecomment-298700043

**Comment by mclearc** [comment]
> So there could be either useful snippets or discussion littered througout that repo's issues or good ideas in it's code.

Agreed -- though I do want to avoid the level of complexity evinced there. My thought is that were I (or someone else) to implement more advanced session restore capability, the thing to do would be to bootstrap off of desktop.el. This would also be fitting given the aim of tabspaces to introduce as little new code as possible and make use of built-in functionality as much as it can.

**Comment by rytswd** [comment]
> Agreed -- though I do want to avoid the level of complexity evinced there. My thought is that were I (or someone else) to implement more advanced session restore capability, the thing to do would be to bootstrap off of desktop.el. 

I agree with relying more on desktop.el -- and on that front, I have to admit that my recent contributions may have been misplaced to be in tabspaces, as I'm not really using desktop.el offerings. When I tried to use it for my setup, it ended up very flakey with inconsistent tab handling, very likely just due to my lack of understanding...

Although I used to use the persp-mode's support to bring back terminals etc., I actually do prefer packages like tabspaces to handle the basic needs without too much complexity. If there is a clear way + documentation to customise to add an extra support like Elfeed, etc., that would be a big plus 👍

**Comment by mclearc** [comment]
Yeah initially I had tried to do session restores via desktop.el but couldn't get it to work right so I went with my simpler if less elegant version. But this will be a thing I keep in mind going forward.

**Pull request merged**
