### PR TITLE
tabspaces-switch-to-or-create-workspace accepts optional tab-name

### PR DESCRIPTION
**Pull request by aaronjensen**
This makes this useful for non-interactive use as well.

### CODE REVIEW

**Comment by aaronjensen** [comment]
hold on this one, improving it.

**Comment by aaronjensen** [comment]
Nevermind, I think this is fine.

**Comment by aaronjensen** [comment]
I pushed a couple of other changes to this branch, feel free to take whichever of the commits you like (if any).

**Review by mclearc — COMMENTED** [review]
I'm not entirely sure I understand the point of this one -- can you say a bit about this last change?

**Comment by aaronjensen** [comment]
It properly addresses [this](https://github.com/mclear-tools/tabspaces/issues/9), though as mentioned in [this comment]https://github.com/mclear-tools/tabspaces/issues/9#issuecomment-1107948585) we might want to consider including the current buffer when setting `buffer-list`.

**Pull request merged**
